apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-service
  namespace: livraison

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service
          image: livraison/notification-service:1.0

          ports:
            - containerPort: 8084

          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: notification-service-secret
                  key: jwt-secret

---
apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: livraison

spec:
  selector:
    app: notification-service

  ports:
    - port: 8084
      targetPort: 8084

  type: ClusterIP