apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-livreurs
  namespace: livraison
spec:
  selector:
    matchLabels:
      app: mysql-livreurs
  serviceName: mysql-livreurs
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-livreurs
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: livreurs_db
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-livreurs
  namespace: livraison
spec:
  selector:
    app: mysql-livreurs
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None