apiVersion: apps/v1
kind: Deployment
metadata:
  name: livreur-service
  namespace: livraison
  labels:
    app: livreur-service
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: livreur-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: livreur-service
    spec:
      containers:
        - name: livreur-service
          image: yemeldev/livreur-service:1.0
          ports:
            - containerPort: 8083
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: livreur-service-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: livreur-service-secret
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: livreur-service-secret
                  key: jwt-secret
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: livreur-service-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: livreur-service-config
                  key: DB_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: livreur-service
  namespace: livraison
  labels:
    app: livreur-service
spec:
  selector:
    app: livreur-service
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP