apiVersion: apps/v1
kind: Deployment
metadata:
  name: colis-service
  namespace: livraison
  labels:
    app: colis-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: colis-service
  template:
    metadata:
      labels:
        app: colis-service
    spec:
      containers:
        - name: colis-service
          image: yemeldev/colis-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: colis-configmap
            - secretRef:
                name: colis-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"