apiVersion: v1
kind: Secret
metadata:
  name: colis-secret
  namespace: livraison
type: Opaque
data:
  # Valeurs encodées en base64
  # echo -n 'root' | base64  →  cm9vdA==
  # echo -n 'jdbc:mysql://mysql-colis:3306/colis_db?useSSL=false&serverTimezone=UTC' | base64
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: cm9vdA==
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL215c3FsLWNvbGlzOjMzMDYvY29saXNfZGI/dXNlU1NMPWZhbHNlJnNlcnZlclRpbWV6b25lPVVUQw==