server:
  port: 8083

spring:
  application:
    name: livreur-service
  datasource:
    url: jdbc:mysql://localhost:3308/users_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET:dev-secret-key-changer-en-production-minimum-32-chars}
  expiration: 86400000